apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-image
  template:
    metadata:
      labels:
        app: dog-image
    spec:
      containers:
      - name: dog-image
        image: dog-image:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
